### ISSUE TITLE
Too much error in run_gc

### ISSUE THREAD

**Issue by akiradeveloper** [akiradeveloper/lol#282]
There happens a lot of panics at `unwrap` in `run_gc`. Reproducer: test_init_cluster and bench

```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /work/lol-core/src/lib.rs:1478:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /work/lol-core/src/lib.rs:1478:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /work/lol-core/src/lib.rs:1478:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /work/lol-core/src/lib.rs:1478:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /work/lol-core/src/lib.rs:1478:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /work/lol-core/src/lib.rs:1478:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /work/lol-core/src/lib.rs:1478:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /work/lol-core/src/lib.rs:1478:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /work/lol-core/src/lib.rs:1478:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /work/lol-core/src/lib.rs:1478:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /work/lol-core/src/lib.rs:1478:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /work/lol-core/src/lib.rs:1478:31
```

```rust
    async fn run_gc(&self, core: Arc<RaftCore>) -> Result<()> {
        let l = self.storage.get_head_index().await?;
        let r = self.get_snapshot_index();
        log::debug!("gc {}..{}", l, r);

        for i in l..r {
            // Remove remaining ack?
            // Not sure it really exists.
            self.ack_chans.write().await.remove(&i);

            let entry = self.storage.get_entry(i).await?;
            let entry = entry.unwrap(); // HERE
            match Command::deserialize(&entry.command) {
                Command::Snapshot { .. } => {
                    // Delete snapshot entry.
                    // There should be snapshot resource to this snapshot entry.
                    core.app.delete_snapshot(i).await?;
                }
                _ => {}
            }
            // Delete the entry.
            // but after everything is successfully deleted.
            self.storage.delete_entry(i).await?;
        }

        Ok(())
    }
```

**Comment by akiradeveloper** [comment]
test_init_cluster runs 100 nodes and it is very CPU heary. So bench is.

When the CPU resource doesn't have much room, replication becomes very slow.

Scenario: In node X, the log has entries from [a,b] and b+1 isn't come soon. In the leader node, snapshot (>b+1) is made and replicated to X then there is a gap from [b+1, X). X tried to run GC [a,X) that occurs the runtime error.
