### ISSUE TITLE
bench: file backend has stability issue 

### ISSUE THREAD

**Issue by akiradeveloper** [akiradeveloper/lol#284]
In bench, we see the file-backend has some issue.

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))', lol-core/src/storage/persistency.rs:49:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))', lol-core/src/storage/persistency.rs:49:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))', lol-core/src/storage/persistency.rs:49:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', /work/lol-core/src/thread/compaction.rs:26:22
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', /work/lol-core/src/thread/compaction.rs:26:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', /work/lol-core/src/thread/compaction.rs:26:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: task was cancelled', lol-core/src/thread/replication.rs:21:65
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: task was cancelled', lol-core/src/thread/replication.rs:21:65
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: task was cancelled', lol-core/src/thread/replication.rs:21:65
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: task was cancelled', /work/lol-core/src/thread/commit.rs:18:77
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: task was cancelled', lol-core/src/thread/replication.rs:21:65
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: task was cancelled', lol-core/src/thread/replication.rs:21:65
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: task was cancelled', lol-core/src/thread/replication.rs:21:65
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: task was cancelled', lol-core/src/thread/replication.rs:21:65
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: task was cancelled', lol-core/src/thread/replication.rs:21:65
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: task was cancelled', lol-core/src/thread/replication.rs:21:65
test bench_commit_huge_16_file  ... bench: 118,503,864 ns/iter (+/- 55,690,056)
```

```
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))', lol-core/src/storage/persistency.rs:49:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))', lol-core/src/storage/persistency.rs:49:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))', lol-core/src/storage/persistency.rs:49:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))', lol-core/src/storage/persistency.rs:49:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))', lol-core/src/storage/persistency.rs:49:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))', lol-core/src/storage/persistency.rs:49:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))', lol-core/src/storage/persistency.rs:49:51
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))', lol-core/src/storage/persistency.rs:49:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))', lol-core/src/storage/persistency.rs:49:51
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))', lol-core/src/storage/persistency.rs:49:51
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))', lol-core/src/storage/persistency.rs:49:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))', lol-core/src/storage/persistency.rs:49:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))', lol-core/src/storage/persistency.rs:49:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))', lol-core/src/storage/persistency.rs:49:51
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', /work/lol-core/src/thread/compaction.rs:26:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', /work/lol-core/src/thread/compaction.rs:26:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: task was cancelled', lol-core/src/thread/replication.rs:21:65
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: background task failed', /work/lol-core/src/thread/compaction.rs:26:22
test bench_commit_huge_64_file  ... bench: 227,706,713 ns/iter (+/- 78,259,479)
```

Since the error messages aren't see in n=1 case and see only one line in n=4, this should be related to the high load.

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))', lol-core/src/storage/persistency.rs:49:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test bench_commit_huge_4_file   ... bench:  73,858,267 ns/iter (+/- 48,619,847)
```

**Comment by akiradeveloper** [comment]
persistency.rs:49 is 

```rust
impl From<Vec<u8>> for Ballot {
    fn from(x: Vec<u8>) -> Self {
        let x: BallotB = bincode::deserialize(&x).unwrap(); // here
```

Let's think about why not occurring on `Entry`? The difference is ballot is overwritten.

```rust
    async fn save_ballot(&self, v: Ballot) -> Result<()> {
        let path = self.ballot_path();
        let bin: Vec<u8> = v.into();
        tokio::fs::write(path, bin).await?;
        Ok(())
    }
```

The error message

```
`Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))'
```

should be meaning partial write of the content.

So let's first rewrite this by mv from temporary space instead of write.

**Comment by akiradeveloper** [comment]
```rust
thread 'tokio-runtime-worker' panicked at 'bin len=0', lol-core/src/storage/persistency.rs:53:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'bin len=0', lol-core/src/storage/persistency.rs:53:17
thread 'tokio-runtime-worker' panicked at 'bin len=0', lol-core/src/storage/persistency.rs:53:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'bin len=0', lol-core/src/storage/persistency.rs:53:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'bin len=0', lol-core/src/storage/persistency.rs:53:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'bin len=0', lol-core/src/storage/persistency.rs:53:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', /work/lol-core/src/thread/compaction.rs:26:22
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', /work/lol-core/src/thread/compaction.rs:26:22
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: noop entry for term 8 isn't committed yet. (> 5)', lol-core/src/server.rs:261:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: task was cancelled', lol-core/src/thread/replication.rs:21:65
test bench_commit_huge_16_file  ... FAILED
```

The error is due to the file length is 0. This may be caused by 

1. The ballot is read after the file is created but being written.
2. The ballot data is lost.

Because using atomicwrites in ballot erases these errors, I suspect 1.

**Comment by akiradeveloper** [comment]
Protecting both ballot and entries by atomicwrites somehow stalls the test. The library always flushes the data and I guess this is causing something bad on the system behavior.

**Comment by akiradeveloper** [comment]
If I disable fold snapshot from kvs-server this error disappear.

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', /work/lol-core/src/thread/compaction.rs:26:22
```

So it is likely snapshotting has a bug.

**Comment by akiradeveloper** [comment]
```
[lol-core/src/lib.rs:1426] port = 42515
[lol-core/src/lib.rs:1426] cur_snapshot_index = 150
[lol-core/src/lib.rs:1426] new_snapshot_index = 259

[lol-core/src/lib.rs:1478] "gc" = "gc"
[lol-core/src/lib.rs:1478] port = 42515
[lol-core/src/lib.rs:1478] l = 150
[lol-core/src/lib.rs:1478] r = 150

[lol-core/src/lib.rs:1426] port = 42515
[lol-core/src/lib.rs:1426] cur_snapshot_index = 150
[lol-core/src/lib.rs:1426] new_snapshot_index = 272

[lol-core/src/lib.rs:1478] "gc" = "gc"
[lol-core/src/lib.rs:1478] port = 42515
[lol-core/src/lib.rs:1478] l = 150
[lol-core/src/lib.rs:1478] r = 259

thread 'tokio-runtime-worker' panicked at '42515: 223 not found', /work/lol-core/src/lib.rs:1429:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This could be the scenario:

1. compaction [150,259] started (comp#1)
2. gc [150,150) started (gc#1)
3. comp#1 schedules a insertion of snapshot entry 259 and returned
4. compaction [150,272) started (comp#2)
5. snapshot entry 259 was inserted
6. gc [150,259) started (gc#2)
7. comp#2 tried to get entry 223 after gc#2 deleted it.
